name: Graviton Runner Start

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ec2-start:
    runs-on: ubuntu-latest

    steps:
      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Start EC2 instance
      - name: Start EC2 instance
        run: |
          aws ec2 start-instances --instance-ids i-0133c8f6344ff0d86